// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal.Context;

#nullable disable

namespace ProyectoFinal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230110171600_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinal.Modelo.CLIENTE", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cliente"));

                    b.Property<string>("correo_cliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dir_cliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nombre_cliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono_cliente")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("id_cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoFinal.Modelo.CONDICION", b =>
                {
                    b.Property<int>("id_condicion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_condicion"));

                    b.Property<string>("desc_condicion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_condicion");

                    b.ToTable("Condiciones");
                });

            modelBuilder.Entity("ProyectoFinal.Modelo.FORMA_PAGO", b =>
                {
                    b.Property<int>("id_forma_pago")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_forma_pago"));

                    b.Property<string>("des_forma_pago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_forma_pago");

                    b.ToTable("FormasPagos");
                });

            modelBuilder.Entity("ProyectoFinal.Modelo.INMUEBLE", b =>
                {
                    b.Property<int>("id_inmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_inmueble"));

                    b.Property<int>("costo_inmueble")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<string>("desc_inmueble")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("id_tipo_inmueble")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<string>("ubic_inmueble")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_inmueble");

                    b.ToTable("Inmuebles");
                });

            modelBuilder.Entity("ProyectoFinal.Modelo.TIPO_INMUEBLE", b =>
                {
                    b.Property<int>("id_tipo_inmueble")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipo_inmueble"));

                    b.Property<string>("desc_tipo_inmueble")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_tipo_inmueble");

                    b.ToTable("TiposInmuebles");
                });

            modelBuilder.Entity("ProyectoFinal.Modelo.VENTA", b =>
                {
                    b.Property<int>("id_venta")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_venta"));

                    b.Property<string>("desc_venta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("fecha_venta")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_cliente")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("id_condicion")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("id_forma_pago")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("id_inmueble")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("total_general")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<int>("total_iva")
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    b.Property<int>("total_venta")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("id_venta");

                    b.ToTable("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
